services:
  weather4agents-api:
    image: giogdev/weather4agents:latest
    container_name: weather4agents-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - C:\WeatherData:/app/weather-data

    restart: unless-stopped
